import { Employee } from "./app/(routes)/dashboard/columns"

export const employeeData: Employee[] = [
  {
    "id": "1",
    "name": "Jammal Stivey",
    "email": "jstivey0@google.com.br",
    "joined": "1/31/2024",
    "technology": "Blockchain",
    "position": "Fulltime",
    "present": "73",
    "absent": "1",
    "seek_leaves": "6",
    "paid_leaves": "2"
  }, {
    "id": "2",
    "name": "Reuven Loveless",
    "email": "rloveless1@usatoday.com",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "9/21/2023",
    "present": "22",
    "absent": "1",
    "seek_leaves": "15",
    "paid_leaves": "1"
  }, {
    "id": "3",
    "name": "Franchot Waymont",
    "email": "fwaymont2@google.es",
    "technology": "MEARN",
    "position": "Intern",
    "joined": "1/5/2024",
    "present": "4",
    "absent": "2",
    "seek_leaves": "11",
    "paid_leaves": "1"
  }, {
    "id": "4",
    "name": "Davina Callicott",
    "email": "dcallicott3@dyndns.org",
    "technology": "Testing",
    "position": "Fulltime",
    "joined": "1/3/2024",
    "present": "58",
    "absent": "0",
    "seek_leaves": "12",
    "paid_leaves": "2"
  }, {
    "id": "5",
    "name": "Lorain Godthaab",
    "email": "lgodthaab4@si.edu",
    "technology": "Testing",
    "position": "Fulltime",
    "joined": "4/16/2024",
    "present": "12",
    "absent": "9",
    "seek_leaves": "0",
    "paid_leaves": "6"
  }, {
    "id": "6",
    "name": "Madalyn Gilliver",
    "email": "mgilliver5@discuz.net",
    "technology": "Testing",
    "position": "Fulltime",
    "joined": "12/14/2023",
    "present": "87",
    "absent": "1",
    "seek_leaves": "6",
    "paid_leaves": "1"
  }, {
    "id": "7",
    "name": "Lonnie Demelt",
    "email": "ldemelt6@quantcast.com",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "2/19/2024",
    "present": "62",
    "absent": "3",
    "seek_leaves": "20",
    "paid_leaves": "2"
  }, {
    "id": "8",
    "name": "Saxe Ca",
    "email": "sca7@creativecommons.org",
    "technology": "Android",
    "position": "Intern",
    "joined": "1/16/2024",
    "present": "91",
    "absent": "14",
    "seek_leaves": "9",
    "paid_leaves": "1"
  }, {
    "id": "9",
    "name": "Arlie Butterly",
    "email": "abutterly8@tripadvisor.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "4/8/2024",
    "present": "36",
    "absent": "1",
    "seek_leaves": "0",
    "paid_leaves": "0"
  }, {
    "id": "10",
    "name": "Tammie Casperri",
    "email": "tcasperri9@gizmodo.com",
    "technology": "Testing",
    "position": "Intern",
    "joined": "8/4/2023",
    "present": "66",
    "absent": "4",
    "seek_leaves": "0",
    "paid_leaves": "3"
  }, {
    "id": "11",
    "name": "Rodger Francklyn",
    "email": "rfrancklyna@topsy.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "9/3/2023",
    "present": "67",
    "absent": "1",
    "seek_leaves": "5",
    "paid_leaves": "2"
  }, {
    "id": "12",
    "name": "Caryl Niccols",
    "email": "cniccolsb@japanpost.jp",
    "technology": "Blockchain",
    "position": "Intern",
    "joined": "4/18/2024",
    "present": "24",
    "absent": "1",
    "seek_leaves": "0",
    "paid_leaves": "1"
  }, {
    "id": "13",
    "name": "Donni Kleinlerer",
    "email": "dkleinlererc@phpbb.com",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "3/9/2024",
    "present": "84",
    "absent": "9",
    "seek_leaves": "11",
    "paid_leaves": "9"
  }, {
    "id": "14",
    "name": "Barbie Mendez",
    "email": "bmendezd@timesonline.co.uk",
    "technology": "MEARN",
    "position": "Fulltime",
    "joined": "9/14/2023",
    "present": "83",
    "absent": "4",
    "seek_leaves": "8",
    "paid_leaves": "2"
  }, {
    "id": "15",
    "name": "Ferdinanda Isacke",
    "email": "fisackee@soup.io",
    "technology": "Blockchain",
    "position": "Intern",
    "joined": "7/15/2023",
    "present": "5",
    "absent": "8",
    "seek_leaves": "18",
    "paid_leaves": "1"
  }, {
    "id": "16",
    "name": "Doy Rubega",
    "email": "drubegaf@intel.com",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "11/22/2023",
    "present": "69",
    "absent": "1",
    "seek_leaves": "0",
    "paid_leaves": "4"
  }, {
    "id": "17",
    "name": "Liv Gammel",
    "email": "lgammelg@odnoklassniki.ru",
    "technology": "Android",
    "position": "Intern",
    "joined": "10/20/2023",
    "present": "13",
    "absent": "8",
    "seek_leaves": "10",
    "paid_leaves": "2"
  }, {
    "id": "18",
    "name": "Kore Rattray",
    "email": "krattrayh@dagondesign.com",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "9/3/2023",
    "present": "71",
    "absent": "4",
    "seek_leaves": "7",
    "paid_leaves": "1"
  }, {
    "id": "19",
    "name": "Zorah Kuhlmey",
    "email": "zkuhlmeyi@noaa.gov",
    "technology": "MEARN",
    "position": "Fulltime",
    "joined": "7/9/2023",
    "present": "39",
    "absent": "6",
    "seek_leaves": "17",
    "paid_leaves": "2"
  }, {
    "id": "20",
    "name": "Addison Tabbitt",
    "email": "atabbittj@jugem.jp",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "4/15/2024",
    "present": "88",
    "absent": "1",
    "seek_leaves": "3",
    "paid_leaves": "0"
  }, {
    "id": "21",
    "name": "Hazel Chrishop",
    "email": "hchrishopk@unblog.fr",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "10/24/2023",
    "present": "43",
    "absent": "1",
    "seek_leaves": "2",
    "paid_leaves": "1"
  }, {
    "id": "22",
    "name": "Isahella M'cowis",
    "email": "imcowisl@paginegialle.it",
    "technology": "MEARN",
    "position": "Intern",
    "joined": "7/4/2023",
    "present": "96",
    "absent": "1",
    "seek_leaves": "16",
    "paid_leaves": "4"
  }, {
    "id": "23",
    "name": "Maudie Dugdale",
    "email": "mdugdalem@accuweather.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "11/13/2023",
    "present": "57",
    "absent": "0",
    "seek_leaves": "20",
    "paid_leaves": "1"
  }, {
    "id": "24",
    "name": "Sebastien Rymer",
    "email": "srymern@webmd.com",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "3/21/2024",
    "present": "49",
    "absent": "1",
    "seek_leaves": "12",
    "paid_leaves": "2"
  }, {
    "id": "25",
    "name": "Ricky Rouff",
    "email": "rrouffo@ted.com",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "8/11/2023",
    "present": "80",
    "absent": "1",
    "seek_leaves": "15",
    "paid_leaves": "8"
  }, {
    "id": "26",
    "name": "Rollin Abernethy",
    "email": "rabernethyp@ifeng.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "1/3/2024",
    "present": "35",
    "absent": "1",
    "seek_leaves": "12",
    "paid_leaves": "3"
  }, {
    "id": "27",
    "name": "Cristabel MacTeague",
    "email": "cmacteagueq@mozilla.com",
    "technology": "Testing",
    "position": "Fulltime",
    "joined": "11/17/2023",
    "present": "23",
    "absent": "1",
    "seek_leaves": "14",
    "paid_leaves": "1"
  }, {
    "id": "28",
    "name": "Massimiliano Jeal",
    "email": "mjealr@elpais.com",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "1/27/2024",
    "present": "94",
    "absent": "3",
    "seek_leaves": "0",
    "paid_leaves": "4"
  }, {
    "id": "29",
    "name": "Andee Ramsbottom",
    "email": "aramsbottoms@flickr.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "11/28/2023",
    "present": "29",
    "absent": "8",
    "seek_leaves": "13",
    "paid_leaves": "4"
  }, {
    "id": "30",
    "name": "Alidia Sommerfeld",
    "email": "asommerfeldt@sitemeter.com",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "12/31/2023",
    "present": "32",
    "absent": "1",
    "seek_leaves": "15",
    "paid_leaves": "1"
  }, {
    "id": "31",
    "name": "Ceil Clarricoates",
    "email": "cclarricoatesu@mysql.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "8/11/2023",
    "present": "94",
    "absent": "1",
    "seek_leaves": "16",
    "paid_leaves": "0"
  }, {
    "id": "32",
    "name": "Elnar Pitway",
    "email": "epitwayv@behance.net",
    "technology": "MEARN",
    "position": "Intern",
    "joined": "6/15/2023",
    "present": "42",
    "absent": "0",
    "seek_leaves": "20",
    "paid_leaves": "6"
  }, {
    "id": "33",
    "name": "Beaufort Basley",
    "email": "bbasleyw@miibeian.gov.cn",
    "technology": "MEARN",
    "position": "Intern",
    "joined": "8/19/2023",
    "present": "60",
    "absent": "6",
    "seek_leaves": "13",
    "paid_leaves": "2"
  }, {
    "id": "34",
    "name": "Jojo Trimbey",
    "email": "jtrimbeyx@gnu.org",
    "technology": "MEARN",
    "position": "Fulltime",
    "joined": "10/23/2023",
    "present": "98",
    "absent": "1",
    "seek_leaves": "14",
    "paid_leaves": "1"
  }, {
    "id": "35",
    "name": "Marsiella Gissop",
    "email": "mgissopy@cmu.edu",
    "technology": "Blockchain",
    "position": "Intern",
    "joined": "12/19/2023",
    "present": "46",
    "absent": "2",
    "seek_leaves": "18",
    "paid_leaves": "4"
  }, {
    "id": "36",
    "name": "Margi Busfield",
    "email": "mbusfieldz@umn.edu",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "8/9/2023",
    "present": "58",
    "absent": "4",
    "seek_leaves": "6",
    "paid_leaves": "0"
  }, {
    "id": "37",
    "name": "Veronika Larive",
    "email": "vlarive10@spiegel.de",
    "technology": "MEARN",
    "position": "Fulltime",
    "joined": "3/25/2024",
    "present": "22",
    "absent": "5",
    "seek_leaves": "19",
    "paid_leaves": "1"
  }, {
    "id": "38",
    "name": "Denney Sutty",
    "email": "dsutty11@mit.edu",
    "technology": "Android",
    "position": "Intern",
    "joined": "3/24/2024",
    "present": "8",
    "absent": "1",
    "seek_leaves": "11",
    "paid_leaves": "5"
  }, {
    "id": "39",
    "name": "Morty Gealy",
    "email": "mgealy12@tripod.com",
    "technology": "Testing",
    "position": "Fulltime",
    "joined": "12/12/2023",
    "present": "46",
    "absent": "0",
    "seek_leaves": "15",
    "paid_leaves": "1"
  }, {
    "id": "40",
    "name": "Nate Brittles",
    "email": "nbrittles13@miibeian.gov.cn",
    "technology": "Blockchain",
    "position": "Fulltime",
    "joined": "10/14/2023",
    "present": "32",
    "absent": "5",
    "seek_leaves": "5",
    "paid_leaves": "9"
  }, {
    "id": "41",
    "name": "Kelbee Kingett",
    "email": "kkingett14@mediafire.com",
    "technology": "Testing",
    "position": "Intern",
    "joined": "8/5/2023",
    "present": "2",
    "absent": "6",
    "seek_leaves": "4",
    "paid_leaves": "2"
  }, {
    "id": "42",
    "name": "Devonna Selburn",
    "email": "dselburn15@alibaba.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "12/19/2023",
    "present": "5",
    "absent": "1",
    "seek_leaves": "6",
    "paid_leaves": "2"
  }, {
    "id": "43",
    "name": "Berne Kattenhorn",
    "email": "bkattenhorn16@twitter.com",
    "technology": "Blockchain",
    "position": "Intern",
    "joined": "1/31/2024",
    "present": "3",
    "absent": "2",
    "seek_leaves": "13",
    "paid_leaves": "2"
  }, {
    "id": "44",
    "name": "Neddy Lorant",
    "email": "nlorant17@elegantthemes.com",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "12/1/2023",
    "present": "93",
    "absent": "4",
    "seek_leaves": "6",
    "paid_leaves": "1"
  }, {
    "id": "45",
    "name": "Larisa Learoyd",
    "email": "llearoyd18@cbsnews.com",
    "technology": "Android",
    "position": "Intern",
    "joined": "9/20/2023",
    "present": "81",
    "absent": "1",
    "seek_leaves": "17",
    "paid_leaves": "8"
  }, {
    "id": "46",
    "name": "Benny Joontjes",
    "email": "bjoontjes19@trellian.com",
    "technology": "MEARN",
    "position": "Intern",
    "joined": "10/22/2023",
    "present": "29",
    "absent": "1",
    "seek_leaves": "14",
    "paid_leaves": "1"
  }, {
    "id": "47",
    "name": "Theresa Tripcony",
    "email": "ttripcony1a@github.io",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "2/11/2024",
    "present": "57",
    "absent": "1",
    "seek_leaves": "9",
    "paid_leaves": "0"
  }, {
    "id": "48",
    "name": "Land Steenson",
    "email": "lsteenson1b@1688.com",
    "technology": "MEARN",
    "position": "Fulltime",
    "joined": "2/7/2024",
    "present": "9",
    "absent": "7",
    "seek_leaves": "4",
    "paid_leaves": "1"
  }, {
    "id": "49",
    "name": "Noe De Beauchemp",
    "email": "nde1c@xing.com",
    "technology": "Testing",
    "position": "Intern",
    "joined": "11/13/2023",
    "present": "73",
    "absent": "1",
    "seek_leaves": "7",
    "paid_leaves": "6"
  }, {
    "id": "50",
    "name": "Joyce Cuss",
    "email": "jcuss1d@state.gov",
    "technology": "Android",
    "position": "Fulltime",
    "joined": "5/12/2024",
    "present": "15",
    "absent": "1",
    "seek_leaves": "12",
    "paid_leaves": "5"
  }

]